version: '3.8'

# Development override - for hot reload without Docker builds
services:
  # Only run PostgreSQL in Docker
  postgres:
    image: postgres:15-alpine
    container_name: usasset-postgres-dev
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: localpassword123
      POSTGRES_DB: usasset
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: