export const DEFAULT_PORT = 3000;
export const DEFAULT_TEST_PORT = 8080;

export const DATABASE_RETRY_MAX_ATTEMPTS = 5;
export const DATABASE_RETRY_BASE_DELAY = 1000;
export const DATABASE_RETRY_MULTIPLIER = 2;

export const HTTP_STATUS_OK = 200;

export const HEALTH_CHECK_TIMEOUT = 1000;
export const MILLISECONDS_PER_SECOND = 1000;
