-- AlterTable
ALTER TABLE "public"."assets" ADD COLUMN     "actualPowerKw" DECIMAL(10,3),
ADD COLUMN     "annualCarbonEmissions" DECIMAL(12,2),
ADD COLUMN     "annualGasConsumption" DECIMAL(12,2),
ADD COLUMN     "annualOperatingDays" INTEGER,
ADD COLUMN     "assetCategoryName" TEXT,
ADD COLUMN     "assetLocation" TEXT,
ADD COLUMN     "assetSizeRounded" TEXT,
ADD COLUMN     "beltQuantity" INTEGER,
ADD COLUMN     "beltSize" TEXT,
ADD COLUMN     "classId" TEXT,
ADD COLUMN     "customerName" TEXT,
ADD COLUMN     "depreciationMethod" TEXT,
ADD COLUMN     "disposalCost" DECIMAL(12,2),
ADD COLUMN     "drawingAbbreviation" TEXT,
ADD COLUMN     "energyEfficiencyRating" TEXT,
ADD COLUMN     "energyEfficiencyValue" DECIMAL(10,2),
ADD COLUMN     "equipNameId" TEXT,
ADD COLUMN     "equipServedBy" TEXT,
ADD COLUMN     "estimatedAnnualElectricityCost" DECIMAL(12,2),
ADD COLUMN     "estimatedAnnualGasCost" DECIMAL(12,2),
ADD COLUMN     "estimatedOperatingHours" INTEGER,
ADD COLUMN     "estimatedReplacementDate" TIMESTAMP(3),
ADD COLUMN     "filterQuantity" INTEGER,
ADD COLUMN     "filterSize" TEXT,
ADD COLUMN     "filterType" TEXT,
ADD COLUMN     "floorName" TEXT,
ADD COLUMN     "gasConsumptionRate" DECIMAL(10,3),
ADD COLUMN     "idUnit" TEXT,
ADD COLUMN     "industryServiceLife" INTEGER,
ADD COLUMN     "legacyBranchId" TEXT,
ADD COLUMN     "legacyClientSiteEquipmentName" TEXT,
ADD COLUMN     "legacyClientSiteEquipmentRn" TEXT,
ADD COLUMN     "legacyInternalAssetId" TEXT,
ADD COLUMN     "legacyUsAssetId" TEXT,
ADD COLUMN     "legacyUseAssetId" TEXT,
ADD COLUMN     "loadFactor" DECIMAL(3,2),
ADD COLUMN     "note1" TEXT,
ADD COLUMN     "note1Subject" TEXT,
ADD COLUMN     "note2" TEXT,
ADD COLUMN     "note2Subject" TEXT,
ADD COLUMN     "note3" TEXT,
ADD COLUMN     "note3Subject" TEXT,
ADD COLUMN     "note4" TEXT,
ADD COLUMN     "note4Subject" TEXT,
ADD COLUMN     "note5" TEXT,
ADD COLUMN     "note5Subject" TEXT,
ADD COLUMN     "note6" TEXT,
ADD COLUMN     "note6Subject" TEXT,
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "numberOfCircuits" INTEGER,
ADD COLUMN     "observedRemainingLife" INTEGER,
ADD COLUMN     "overrideElectricityRate" DECIMAL(6,4),
ADD COLUMN     "overrideGasRate" DECIMAL(6,4),
ADD COLUMN     "ownerId" TEXT,
ADD COLUMN     "peakDemandKw" DECIMAL(10,3),
ADD COLUMN     "powerFactor" DECIMAL(3,2),
ADD COLUMN     "preconSystem" TEXT,
ADD COLUMN     "preconTag" TEXT,
ADD COLUMN     "propertyName" TEXT,
ADD COLUMN     "propertyZoneServed" TEXT,
ADD COLUMN     "ratingName" TEXT,
ADD COLUMN     "ratingValue" TEXT,
ADD COLUMN     "refrigerant" TEXT,
ADD COLUMN     "refrigerantDefaultDescription" TEXT,
ADD COLUMN     "refrigerantDescription" TEXT,
ADD COLUMN     "refrigerantQuantity" DECIMAL(10,2),
ADD COLUMN     "returnFanMotorSize" TEXT,
ADD COLUMN     "salvageValue" DECIMAL(12,2),
ADD COLUMN     "serviceId" TEXT,
ADD COLUMN     "subSystemClass" TEXT,
ADD COLUMN     "subSystemClassification" TEXT,
ADD COLUMN     "subSystemId" TEXT,
ADD COLUMN     "subSystemType" TEXT,
ADD COLUMN     "supplyFanMotorSize" TEXT,
ADD COLUMN     "systemTypeId" TEXT,
ADD COLUMN     "title" TEXT,
ADD COLUMN     "totalAnnualEnergyCost" DECIMAL(12,2),
ADD COLUMN     "type" TEXT,
ADD COLUMN     "useOverrideRates" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "vendor" TEXT,
ADD COLUMN     "vendorWebsite" TEXT,
ADD COLUMN     "verified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "warrantyExpirationDate" TIMESTAMP(3),
ADD COLUMN     "xCoordinate" DECIMAL(10,6),
ADD COLUMN     "yCoordinate" DECIMAL(10,6);

-- CreateIndex
CREATE INDEX "assets_trade_idx" ON "public"."assets"("trade");

-- CreateIndex
CREATE INDEX "assets_buildingName_idx" ON "public"."assets"("buildingName");

-- CreateIndex
CREATE INDEX "assets_floor_idx" ON "public"."assets"("floor");
